import type { Metadata } from "next";
// import localFont from "next/font/local";
import "./globals.css";
import {
    ClerkProvider,
} from '@clerk/nextjs'
import Header from "@/components/Header";

// const geistSans = localFont({
//     src: "./fonts/GeistVF.woff",
//     variable: "--font-geist-sans",
//     weight: "100 900",
// });
// const geistMono = localFont({
//     src: "./fonts/GeistMonoVF.woff",
//     variable: "--font-geist-mono",
//     weight: "100 900",
// });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {

    
    return (
        <ClerkProvider>
            <html lang="en">
                <body>
                    {/* <header>
                    <div className="left">
                        <img src="/icons/Exclusive.svg" alt="logo" />
                    </div>
                    <div className="center">
                        <Link href="/">Home</Link>
                        <Link href="/contact">Contact</Link>
                        <Link href="/about">About</Link>
                        <Link href="/sign-up">Sign Up</Link>
                    </div>
                    <div className="right">
                        <input type="text" name="search" className="bg-[#f5f5f5]"/>

                    </div>
                </header> */}
                    <Header/>
                    
                    {children}
                </body>
            </html>
        </ClerkProvider>
    );
}
